# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/get/project/1
Accept: application/json

###

GET http://127.0.0.1:8000/get/project/2
Accept: application/json

###

GET http://127.0.0.1:8000/get/project/3
Accept: application/json

###

GET http://127.0.0.1:8000/get/project/4
Accept: application/json

###

DELETE http://127.0.0.1:8000/delete/project/3
Accept: application/json

###

POST http://127.0.0.1:8000/upload/project
Content-Type: application/json

{
  "name": "TheProject",
  "repositories": [
    {
      "name": "Repo1",
      "tasks": [
        {
          "name": "Task1",
          "completed": true,
          "due_date": "2023-12-31",
          "priority": "Aucune",
          "assignee": "John Doe",
          "subtasks": [
            {"name": "Subtask1", "completed": true},
            {"name": "Subtask2", "completed": true}
          ]
        },
        {
          "name": "Task2",
          "completed": true,
          "due_date": "2023-12-31",
          "priority": "Aucune",
          "assignee": "Jane Doe",
          "subtasks": [
            {"name": "Subtask1", "completed": true}
          ]
        }
      ]
    }
  ]
}



###

POST http://127.0.0.1:8000/upload/project
Content-Type: application/json

{
        "name": "ThePostEmptyProject",
        "repositories": []
    }

###

POST http://127.0.0.1:8000/update/project/1212
Content-Type: application/json

{
        "name": "TheReplacedEmptyProject",
        "repositories": []
    }

###

POST http://127.0.0.1:8000/update/project/1
Content-Type: application/json

{
  "name": "TheOverwrittenProject",
  "repositories": [
    {
      "name": "Repo1",
      "tasks": [
        {
          "name": "Task1",
          "completed": true,
          "due_date": "2023-12-31",
          "priority": "Aucune",
          "assignee": "John Doe",
          "subtasks": [
            {"name": "Subtask1", "completed": true},
            {"name": "Subtask2", "completed": true}
          ]
        },
        {
          "name": "Task2",
          "completed": true,
          "due_date": "2023-12-31",
          "priority": "Aucune",
          "assignee": "Jane Doe",
          "subtasks": [
            {"name": "Subtask1", "completed": true}
          ]
        }
      ]
    }
  ]
}

###

GET http://127.0.0.1:8000/get/all_projects
Accept: application/json